### ISSUE TITLE
Game refuses to launch on 1.20.6

### ISSUE THREAD

**Issue by Psora1** [Grayray75/FPS-Display#14]
Game refuses to launch on Fabric 1.20.6 because of hard lock on version number for current build of FPS-Display.

**Comment by Grayray75** [comment]
I know, I will publish an update for 1.20.6 soon.

**Comment by Grayray75** [comment]
Just updated the mod to 1.20.5/6 :+1:
https://modrinth.com/mod/fpsdisplay/version/4.1.0+1.20.5
