### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by JasonHorkles** [Grayray75/FPS-Display#17]
Hi! It seems there were some changes in 1.21 that make the mod no longer work (even when version bypassed in Fabric):
`[Render thread/INFO]: fpsdisplay.mixins.json:MinecraftClientAccessor from mod fpsdisplay->@Accessor[FIELD_GETTER]::getCurrentFps()I should be static as its target is`

**Comment by Grayray75** [comment]
Just released an update for 1.21, enjoy!
https://modrinth.com/mod/fpsdisplay/version/4.2.0+1.21

**Comment by JasonHorkles** [comment]
Thank you!!
