### ISSUE TITLE
Option to set the size

### ISSUE THREAD

**Issue by justalemon** [Grayray75/FPS-Display#7]
Hi, are there any plans to implement an option to set the text size? I tried to use the mod to see my current framerate on VR but is too small.

Thanks for the good mod!

**Comment by Grayray75** [comment]
Hi, I implemented this option in 8ad98dc and I will release a new version soon.
Now you can display your FPS in any size you like :)

Just change the size in the option menu:
![options](https://user-images.githubusercontent.com/69988482/160283239-164df4ce-bdd9-420b-be88-424f2a0f77ed.png)

and enjoy 🙂
![2022-03-27_15 13 43](https://user-images.githubusercontent.com/69988482/160283268-8e839853-2247-4e87-8c01-72d5409d0e66.png)
