### ISSUE TITLE
Update the 1.8.9 legacy fabric version

### ISSUE THREAD

**Issue by HowardZHY** [Grayray75/FPS-Display#8]
not working on latest LF 1.8.9.

**Comment by Grayray75** [comment]
I know the 1.8.9 version is currently broken... 😞 
Unfortunately, I am very busy at the moment and don't have time to work on my mods.
But I will make a new 1.8.9 version as soon as I have time again.

**Comment by Grayray75** [comment]
Small update: I've completely rewritten the mod so that it no longer requires Cloth Config.
(Cloth Config is still required to change the mod settings ingame, if it's missing, the user will have to edit the config file).
This means that a new legacy fabric version could be coming soon™.

**Comment by Grayray75** [comment]
Finally released an update for 1.8.9 :)

https://modrinth.com/mod/fpsdisplay/version/3.1.0+1.8.9
